### ISSUE TITLE
Event Description: [The relying party specified in the AppliesTo element is not recognized.]. User Advice: [Advise business the request has specified an unrecognised relying party.].

### ISSUE THREAD

**Issue by mahegithub** [bartland-usi/sample-java#13]
Hi Bruce,

Thanks for the sample. it is really helpful. I am working on the USI Verification, I have loaded the M2M keystore.xml (created via RAM for our organization) and I am passing the correct details to the "UsiServiceChannel.java" java code. When I run the "USITest.java" using the PROD URL https://softwareauthorisations.ato.gov.au/R3.0/S007v1.2/service.svc, I get the below error. Please advise if there are any issues with my configuration.

javax.xml.ws.soap.SOAPFaultException: The specified request failed. Event Code: [E2003]. Event Severity: [Normal]. Event Description: [The relying party specified in the AppliesTo element is not recognized.]. User Advice: [Advise business the request has specified an unrecognised relying party.]. Agency Reference: [uuid:edbf7738-*-*-950a-**]. Transaction Id: [*-c28e-4a2c-8876-**].
	at com.sun.xml.ws.security.trust.impl.wssx.WSTrustElementFactoryImpl.checkElement(WSTrustElementFactoryImpl.java:913)
	at com.sun.xml.ws.security.trust.impl.wssx.WSTrustElementFactoryImpl.createRSTRCollectionFrom(WSTrustElementFactoryImpl.java:495)
	at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.parseRSTR(TrustPluginImpl.java:752)
	at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.invokeRST(TrustPluginImpl.java:631)
	at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.process(TrustPluginImpl.java:175)
	at com.sun.xml.ws.security.trust.impl.client.STSIssuedTokenProviderImpl.getIssuedTokenContext(STSIssuedTokenProviderImpl.java:144)
	at com.sun.xml.ws.security.trust.impl.client.STSIssuedTokenProviderImpl.issue(STSIssuedTokenProviderImpl.java:74)
	at com.sun.xml.ws.api.security.trust.client.IssuedTokenManager.getIssuedToken(IssuedTokenManager.java:83)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.invokeTrustPlugin(SecurityClientTube.java:686)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processClientRequestPacket(SecurityClientTube.java:283)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processRequest(SecurityClientTube.java:249)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1136)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1050)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:1019)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:877)
	at com.sun.xml.ws.client.Stub.process(Stub.java:463)
	at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:191)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:108)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:92)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:161)
	at com.sun.proxy.$Proxy47.verifyUSI(Unknown Source)
	at usi.gov.au.USITest.main(USITest.java:128)

**Comment by bartland** [comment]
Thanks for the feedback. Sorry for the delay. I'm not getting notifications.

Turned out to be a case sensitivity issue on the URL (sadly).

But there were some other issues and I've done a cleanup. Confirmed it is now working with PROD.

Let me know how you go.

**Comment by mahegithub** [comment]
Thanks, Bruce. Yes, we contact IT USI and they told us to check the endpoint URL. It is working now. Also, can you please let me know if there are any major updates made to the java code for the USI?

**Comment by mahegithub** [comment]
The SOAP endpoint URL is case-sensitive for the PROD.

**Comment by JoshuaMiles** [comment]
@mahegithub  or @bartland to confirm the actual case of the URL is https://softwareauthorisations.acc.ato.gov.au/R3.0/S007v1.3/Service.svc? I am seeing the link in a few different places (over in the dotnet codebase) and would like to confirm which one I am supposed to use.
