### ISSUE TITLE
3PT USI v4 - At least one security token in the message could not be validated

### ISSUE THREAD

**Issue by mahegithub** [bartland-usi/sample-java#15]
Hi,

We are getting the error when connecting to 3PT USI v4 service:

<s:Reason><s:Text xml:lang="en-AU">At least one security token in the message could not be validated.</s:Text></s:Reason></s:Fault></s:Body></s:Envelope>--------------------

javax.xml.ws.WebServiceException: WSSTUBE0025: Error in Verifying Security in the Inbound Message.
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processClientResponsePacket(SecurityClientTube.java:416)
	at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processResponse(SecurityClientTube.java:338)
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1117)
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1020)
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:989)
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:847)
	at com.sun.xml.ws.client.Stub.process(Stub.java:433)
	at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:161)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131)
	at com.sun.proxy.$Proxy47.verifyUSI(Unknown Source)
	at usi.gov.au.USITest.main(USITest.java:126)
Caused by: javax.xml.ws.soap.SOAPFaultException: Invalid Security Header
	at com.sun.xml.wss.jaxws.impl.SecurityTubeBase.getSOAPFaultException(SecurityTubeBase.java:686)
	at com.sun.xml.wss.jaxws.impl.SecurityTubeBase.getSOAPFaultException(SecurityTubeBase.java:704)
	... 13 more
Caused by: com.sun.xml.wss.impl.WssSoapFaultException: Invalid Security Header
	at com.sun.xml.wss.impl.SecurableSoapMessage.newSOAPFaultException(SecurableSoapMessage.java:319)
	at com.sun.xml.wss.jaxws.impl.SecurityTubeBase.getSOAPFaultException(SecurityTubeBase.java:701)
	... 13 more

**Comment by mahegithub** [comment]
Issue with the 3PT service and now its working as expected.
